language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: ci@radon.app
  api_key:
    secure: 0Iyb+EOl65zPi336J9eLOuNs3rhlHGwa+29NH4hT0rfJjVO48XL7yBzPXZtyDufD6OxAEGKjxMsKiAUMtVuPKAe2MDRUOrjRq6fXcIURqx4FYY33iesQYeV+7Xs/OKINDppotQi2H8qsq//5TWud8Plj9dAARKAlzjcs34CnNgH+9A91DjVIwM+T2Yn/ia3GH6uDfSZrOHuKm++Nqdjy6wgJgmvmkToMBVfzPWN+TpanO+/KMD7A5kDRLf/hKnWTDVcBqcwa1xCfyxbu09uOaDu43bB9XSbzPw5Bc6ZdMK/38V4mHy6HBu61q9vQ/+NYCQ8Nu61djNevWuub2h+bbqSpDF+XmDI7AelB0/n/4hlpsrLj8QhifiFWJWQiHBNjQeXzs3xm56pkaVtnN9prfyaEREu91a5Eb2iapxu9hMOlAdyWbAF9xH59+1PVg5w060TBvgtAO7QPx/Jg4WAhtvJ8VhxHd6uzDDlSt244ZyP+8naoref/lj9X1015R1iqcrPuBP0ZOt4WXD+xKRbY1ibkG8UAQaHbm7ZLqS1l19uxTYUGmN+0XAy8Q17afU+l3Tlgpedn/NyzSG84g6IQ76sI3F1FuCfClebQUenIInFYoYloox96AcYEVTQQrjMVqKbLmHcwUx/Pe02MA1szn4OGeCMsbnWj2GV1cf765AE=
  on:
    tags: true
    repo: RadonApp/radon-extension-plugin-spotify
