language: node_js
node_js:
- '7'
script:
- npm run test
deploy:
  provider: npm
  email: neapp-ci@me.dgardiner.net
  api_key:
    secure: 0WM9ttLqSZOkiCjToEuQl075/ZlHMKsGbP783KRc3HApcjOp5uym5pD2qxecKcqxOume0Ep9W3DAurlHm+A8gNSZCkr7t2p3RKgzgugZgxzj9peLeBPHYyadW/z5TzFu0PnhNgkl10E5KYlruF98Z2cbdEHE3/CYJI9FZE1nKzz5Z/B7KffAYrBqRxVfznX+oX21XovSeTh3dJge5GTXgoJgGg7S1oH8hQNhCyTsP3IwJQIyf/FW0oTgUjkqaAnnexPxh1AHO7iMDc6bQ0EvxdDyrAblQvE8WkovnsM3b2yalXWWsqaV1SpIQCm7fsnM5T4omYG7acf79CHnWk8yR20c9hv5ASV1LQq+ioPEJRLjvfDDAJ2WoU+fm6t0VmT+8Gh9vsNJ3/04PazRfbIN9B6iBePSmN6arJHTe6d+puy2O4HFBWtTMT9euxDurYzKAIzqRzrCUPpH62v792oP6qZMLPL00WTqRlYE3X7iYBaeKRPk5SQLtSTMzRemMsaK3m1p1gNh1NRh0SMB9DvRhQu55W+83nVx4Mm/JFRJIVBIZKYwkAuQ39fT/+464ubcTNak4OpgZ993r4BJh5y1EN69ppdLU2c56edF47lZd94DwJ8PtS1btrQtdyLmM5Clmk/G65jMJ8rJ68vahicP5aHMdxzlSUyass9K2vcArvc=
  on:
    repo: NeApp/neon-extension-source-spotify
    tags: true
